### ISSUE TITLE
de novo sequencing without evaluation

### ISSUE THREAD

**Issue by BenSamy2020** [Noble-Lab/casanovo#10]
Greetings,

Firstly, I would like to thank you for providing this open source tool. I am currently interested to perform de novo sequencing without evaluation. Based on your github page, it was shown to run the command of:

**casanovo --mode=denovo --model_path='path/to/pretrained' --test_data_path='path/to/test' --config_path='path/to/config' --output_path='path/to/output'**

1) Could you assist me on where to obtain the --config_path file?
2) Does the --test_data_path mean the .raw proteomics file?
3) Do you have an example output file from Casanovo?

Regards,
Ben

**Comment by melihyilmaz** [comment]
Hi Ben,
We appreciate your interest in Casanovo! 
1. The config file can be user provided but the default is the [`casanovo/config.py`](https://github.com/Noble-Lab/casanovo/blob/main/casanovo/config.py) we provide in the repo. You can use it as a template for your own config file and provide the path to your file.
2. `test_data_path` denotes the path to the directory where you have the `.mgf` file you want to sequence.
3. I added an example output file [`casanovo_sample_output.csv`](https://github.com/Noble-Lab/casanovo/blob/main/casanovo_sample_output.csv) to the repo.

Let me know if you have other questions, feel free to close the issue otherwise.

**Comment by BenSamy2020** [comment]
Greeting @melihyilmaz,

This is actually a really amazing tool!
I have successfully started the program. Now it is running. Based on the output file you had provided can I request for a program improvement feature?

The improvement I would suggest is to allow a proteomics fasta database to be provided in the command it self. Subsequently, the program would match the denovo sequenced peptides onto the fasta protein database provided and append the fasta header to the corresponding peptides.

I understand this is a huge ask, but this enhancement would improve downstream analysis.

Additionally, I also observed the user warning of:  **UserWarning: You are running on single node with no parallelization, so distributed has no effect.
  rank_zero_warn("You are running on single node with no parallelization, so distributed has no effect.")**

Could you advise me on how to dedicate/allocate sufficient CPU for your program (e.g., --cpu 15). Unfortunately, the options of --cpu or --memory is not available.    

Regards,
Ben

**Comment by guhanrv** [comment]
Hi @BenSamy2020, 

I've been using the program recently and think I can help!
1. You can adjust the number of CPUs in the casanovo/config.py file, which should be found in your `/environment/lib/pythonversion/site-packages/casanovo/config.py` file, on line 30.
2. Yes. If you are able to run `python3` from the command line, `import torch`, and type `torch.cuda.is_available()` and it returns `True`, that means your environment is configured to recognize your GPU, and so all you need to do is change line 31 in the same file as above to `gpus = [0]`. Then, when you run Casanovo, you should see `GPU available: True, used: True` instead.
3. I think the GPU will help lots there. Also, check the `test_batch_size` (line 80 in the same config file) - it's by default set to 1024, so your screen will only update after inferring 1024 peptides. On CPU, that takes a while. So try changing that test batch size to something small and see if you see progress.

Hope this helps!

**Comment by BenSamy2020** [comment]
Greetings @guhanrv,

I am really appreciative of your assistances. With regards to CPUs I will edit line 30 of config.py file.
Unfortunately, pytorch is not available on my PC and I would require to set it up. Additionally, I am a wet lab person. I will have to youtube or google some information on how to set it up before tapping onto my GPUs.

Once again thank alot!

Regards,
Ben
