### ISSUE TITLE
Casanovo with GPU engagement

### ISSUE THREAD

**Issue by BenSamy2020** [Noble-Lab/casanovo#101]
Greeting @melihyilmaz,

By any chance do you have a guide on to set-up Casanovo to utilize GPU?  - (e.g. setting up CUDA environment so I can utilize Casonovo to utilize it)

Regards,
Ben

**Comment by melihyilmaz** [comment]
Hi Ben,

Casanovo automatically utilizes available GPUs in your system. You can refer to [Getting Started](https://casanovo.readthedocs.io/en/latest/getting_started.html) and [FAQ](https://casanovo.readthedocs.io/en/latest/faq.html) page on Casanovo documentation to trouble shoot CUDA related issues as they arise and also open issues here. 

For are a general-purpose installation guide for CUDA Toolkit, you can refer to [this page](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html).

**Comment by BenSamy2020** [comment]
Greetings,

I tried running the following commands on my institute HPC GPU node:

**$**srun -t 1:00:00 -N 1 -p gpuexpress --cpus-per-gpu 6 --mem-per-gpu 21000 --gres=gpu:tesla:1 --pty /bin/bash
**$**source /apps/anaconda3-individual-edition/2020.11/etc/profile.d/conda.sh
**$**conda activate casanovo_env
**$**python casanovo --mode=denovo --peak_path=/home/users/astar/imcb/parthiban/scratch/Casanovo_input_files/*.mzML --output=/home/users/astar/imcb/parthiban/scratch/Casanovo_input_files/Output

I hit the error of:
![image](https://user-images.githubusercontent.com/69944967/204711360-8d5c5b42-98c1-43f7-906e-7447c4e9e4b9.png)

Please do advise me on how to troubleshoot this.

Regards,
Ben

**Comment by wsnoble** [comment]
Remove the word `python` in front of `casanovo` and you should be good to go.

**Comment by BenSamy2020** [comment]
Greetings @wsnoble,

When I do that I hit the warning of:
![image](https://user-images.githubusercontent.com/69944967/204715097-7b8361da-0a52-47bb-9c77-de42fae221e1.png)

Does the warning mean, I am not engaging the GPU?

Regards,
Ben

**Comment by melihyilmaz** [comment]
The warning isn't about GPU usage and is likely safe to ignore. You can check your GPU usage with `nvidia-smi` in real time command while running Casanovo.
