### ISSUE TITLE
Results 

### ISSUE THREAD

**Issue by guhanrv** [Noble-Lab/casanovo#11]
Hello!

I am interested in using Casanovo for inference, and I just wanted to make sure that I am using it correctly.

I am using PyTorch version 1.10.2 with Cuda 11.3 on a machine with a GPU and 8 workers, and adjusted the config.py file accordingly:

```
#Hardware options
num_workers = 8
gpus = [0] #None for CPU, int list to specify GPUs
```

When I run inference on the attached file (renamed to test.mgf.txt so it can attach here), I get the folllowing result:

```
spectrum_id,denovo_seq
0,LLAETLLR
```

However, I know that the inference from MSFragger yields QLEQVIAK, which is the true peptide. I am using the pretrained human weights. Would you mind terribly testing the algorithm on the attached file to see if I am simply using Casanovo wrong? Thank you so much, and I really appreciate the help.

[test.mgf.txt](https://github.com/Noble-Lab/casanovo/files/8187993/test.mgf.txt)

**Comment by melihyilmaz** [comment]
Hi Guhan,

I ran inference with `pretrained_excl_human.ckpt` weights (in addition to few other species) and  obtained the `QLEQVLAK` de novo prediction from the model. Can you check if you're using `preprocess_spec=True` when running the model on your raw data (it's `False` by default)?

**Comment by guhanrv** [comment]
Just a suggestion - you might want to put this in the readme, as it's not clear that this should be done :)

**Comment by melihyilmaz** [comment]
I will change the default `preprocess_spec=True` in the config file. We are planning to create more thorough documentation for Casanovo in the near future. Thank you for your interest!
