### ISSUE TITLE
How to run as scripts?

### ISSUE THREAD

**Issue by feiluoo** [Noble-Lab/casanovo#110]
Thanks for sharing the code!

I clone the repo to my local computer, and was trying to run/debug the casanovo.py. But got errors like the following:

      File "/home/code/casanovo/casanovo/casanovo.py", line 23, in <module>
        from . import __version__
    ImportError: attempted relative import with no known parent package

This seems like to be related to relative imports. Is it possible to run/debug the code as scripts? I want to check what's is going on inside casanovo!

Thank you in advance!

**Comment by wfondrie** [comment]
Hi @feiluoo 👋 - thanks for giving Casanovo a try!

We designed Casanovo as a command line tool, so access as a Python package should be used cautiously. That be said, trying to use Casanovo from the Python interpreter requires it to be installed as a Python package. The easiest way is to install directly from PyPI, using pip:
```
pip install casanovo
```
Once installed, you should be able to import Casanovo as any other Python package:
```python
import casanovo
print(casanovo.__version__)
```

However, if you want to interact with the source code, I recommned an editable installation. First clone the Casanovo repository to your computer:
```
git clone git@github.com:Noble-Lab/casanovo.git
```

Then install the cloned repository with pip. Here, I assume that there is a `casanovo` directory that was created in your working directory:
```
pip install -e ./casanovo
```

Happy exploring! 🎉
