### ISSUE TITLE
Casanovo nonenzymatic model

### ISSUE THREAD

**Issue by piroman999** [Noble-Lab/casanovo#119]
Hello, can I obtain a model pre-trained for non-enzymatic peptide identification, as mentioned in the paper 'Sequence-to-sequence translation from mass spectra to peptides with a transformer model' ?

**Comment by bittremieux** [comment]
Please find the non-enzymatic weights temporarily [here](https://filesender.belnet.be/?s=download&token=2ab70cf5-da1c-4e54-b7d5-f9ced11d33d3).

We're working on new functionality that will make it possible to automatically download different weights in the future (#108) after which we'll publish the non-enzymatic weights together with the default, tryptic, weights on the Releases page.
