### ISSUE TITLE
Casanovo Assigning Multiple Modifications to Single AA

### ISSUE THREAD

**Issue by kostrouc** [Noble-Lab/casanovo#129]
I just noticed that all my casanovo output contains sequences that have 2 or more modifications specified for Cystine. 

For example I have a sequence that reads:
"C+57.021-17.027+42.011C+57.021EEC+57.021LK"

How are we supposed to interpret these .mztab results? Were all the modifications observed and they need to be split into the different versions of each of the modifications for the peptide sequence? Or is this a summation of all the modifications, which to my knowledge cannot occur?

[Example_Output.txt](https://github.com/Noble-Lab/casanovo/files/10539831/Example_Output.txt)

**Comment by melihyilmaz** [comment]
Cystines are predicted to have a static modification, carbamidomethylation, by default (+57.021) and for the sequence you shared, Casanovo seems to have predicted N-terminal NH3 loss and acetylation, which may not be plausible.  

You can see the PTMs Casanovo predicts in the config file [here](https://github.com/Noble-Lab/casanovo/blob/main/casanovo/config.yaml)

**Comment by kostrouc** [comment]
I have noticed that 2-3 modifications can be observed for many predicted amino acids, not just cystine in the beginning of predicted sequences. Preventing more than one assignment would be helpful. It's difficult to filter out these duplicate modifications and replace them with the first occurrence.

```
kostrouchov@ip$ grep "17.027-17" ./sample.mztab
PSM     -17.027-17.027TPEEEERPC+57.021RPPRPPQPPC+57.021PAC+57.021SQHPTTER       2480    null    null    null    null    [MS, MS:1003281, Casanovo, 3.2.1.dev2+gc9ec696] -0.6527986261519345     null    null    5       718.1340942382812       712.7238130068799       ms_run[1]:index=2480    null    null    null     null    0.00008,0.00019,0.31721,0.24468,0.26268,0.27762,0.20828,0.13801,0.26879,0.26221,0.27842,0.65948,0.19925,0.15491,0.85482,0.03296,0.38508,0.10741,0.96392,0.44581,0.16540,0.95694,0.34634,0.31323,0.26294,0.20341,0.16721,0.
kostrouchov@ip$ grep "57.021-17" ./sample.mztab
PSM     C+57.021-17.027QLEDLC+57.021C+57.021GR  370     null    null    null    null    [MS, MS:1003281, Casanovo, 3.2.1.dev2+gc9ec696] -0.6436758259124788     null    null    2       570.330078125   647.2546663168799       ms_run[1]:index=370     null    null    null    null    0.00010,0.86124,0.75261,0.21290,0.16451,0.13427,0.27341,0.45237,0.35290,0.11246,0.60278
kostrouchov@ip$ grep "43.006-17" ./sample.mztab
PSM     +43.006-17.027-17.027+43.006LLC+57.021FDLRPLLLLGTLRK    7484    null    null    null    null    [MS, MS:1003281, Casanovo, 3.2.1.dev2+gc9ec696] 0.5832429447280447      null    null    3       698.755615234375        698.4031750335464       ms_run[1]:index=7484    null    null    null    null    0.00000,0.00003,0.21489,0.41154,0.71471,0.48243,0.19357,0.67029,0.65012,0.68821,0.19096,0.99740,0.99994,0.99999,0.99994,0.99984,0.75264,0.81090,0.14896,0.73851
```

I have attached the corresponding mgf scans that produced this output from casanovo (with a .txt extension).

[sample.mgf.txt](https://github.com/Noble-Lab/casanovo/files/10735995/sample.mgf.txt)

**Comment by bittremieux** [comment]
These predictions are more than likely incorrect. You can see from amino acid confidences (final column) that Casanovo assigns very low scores to those repeated N-terminal modifications. This can happen when the spectra don't contain enough fragments for accurate _de novo_ sequencing, and Casanovo picks something more or less randomly. Removing repeated modifications is unlikely to result in a correct peptide prediction.

In general, only predictions with high scores are confident, and lower-scoring predictions probably should just be discarded (by lack of established FDR procedures in _de novo_ sequencing).
