### ISSUE TITLE
How did Casanovo deal with variable peaks in the encoder ?

### ISSUE THREAD

**Issue by alifare** [Noble-Lab/casanovo#135]
Spectra have a variable number of peaks, how did Casanovo deal with spectra with variable peaks in the encoder?
I cannot find the description of it in the paper _De Novo Mass Spectrometry Peptide Sequencing with a Transformer Model_ , and the Python module _depthcharge.components_ seems to be not open-sourced.

Can anybody explain this to me?

**Comment by wsnoble** [comment]
As mentioned in Section 4.1.1, "The m/z value and intensity are
embedded separately before being summed to yield the input
peak embedding."

Depthcharge is open source and is available [here](https://github.com/wfondrie/depthcharge).

**Comment by XiaojieGan** [comment]
> As mentioned in Section 4.1.1, "The m/z value and intensity are embedded separately before being summed to yield the input peak embedding."
> 
> Depthcharge is open source and is available [here](https://github.com/wfondrie/depthcharge).

So how did Casanovo deal with variable length？ a fixed length？

**Comment by melihyilmaz** [comment]
Casanovo handles variable number of spectral peaks with padding tokens during batching (e.g. see [here](https://github.com/Noble-Lab/casanovo/blob/e6321a7c6d59da5bb48b9e9eabb0b00979d17d01/casanovo/denovo/dataloaders.py#L177) in the repo) and we also select up to 150 most intense peaks per spectrum during preprocessing (see [Spectrum Preprocessing](https://www.nature.com/articles/s41467-024-49731-x) section in our paper).
