### ISSUE TITLE
Multi-GPU is broken

### ISSUE THREAD

**Issue by seantur** [Noble-Lab/casanovo#140]
When running inference on a multi-GPU setup ('ddp' strategy) with n GPUs, the mztab output only has 1/n results.

Unlike #128 I am able to successfully run to completion, but the output is missing results. In that issue it looks like you've had issues with multi-GPU inference in the past, but I didn't see an open bug for it.

After a little digging, it looks like it might be related to this: https://github.com/Lightning-AI/lightning/issues/10618 and the solution is to implement a different callback that gets called per process. I'm not sure of the implications on the current mztab writer strategy.

**Comment by bittremieux** [comment]
Yes, this is a known issue. PyTorch Lightning starts individual processes when running on multiple GPUs, but as a result, when writing the output file, the process that finishes last will overwrite the file that was written during the faster process(es).

For now we recommend using only a single GPU to run inference. You can specify the GPU you want to run on with `CUDA_VISIBLE_DEVICES`. I should make a note of this in the instructions.

Running in training mode correctly supports multiple GPUs.
