### ISSUE TITLE
Multiple warnings when running de novo, and doesn't complete

### ISSUE THREAD

**Issue by neely** [Noble-Lab/casanovo#150]
I am running a single fairly small DDA mgf of a mixture of peptides in de novo mode with built in model. 

`casanovo --mode=denovo --peak_path="F:\2022-8-29 LC Tests\mgfs\2022-8-29_8321_30min.mgf" --output="F:\2022-8-29 LC Tests\casanova\30minv2"`

I have repeated this twice with restarts in between and let it run 1 to 3 hours and it doesn't progress from these initial warnings, but I can tell it is running since my CPU and RAM are maxing out. I assume this is an error I can fix, but I am not sure what parameters in which files to modify. (note I am using pytorch lightning 1.7 based on [this issue](https://github.com/Noble-Lab/casanovo/issues/147))

[30minv2.log](https://github.com/Noble-Lab/casanovo/files/11032165/30minv2.log)

**Comment by neely** [comment]
My laptop definitely doesn't have a GPU.

**Comment by bittremieux** [comment]
That's very likely the issue. This has been vexing us for a while, but we hope to have a fix soon. I'm going to close this issue in favor of #106, where we're tracking the GPU-related problems.
