### ISSUE TITLE
Getting top-k candidates

### ISSUE THREAD

**Issue by cguetot** [Noble-Lab/casanovo#154]
Hi,

I have been reading the documentation for using CasaNovo, and I would like to know if there is a flag or option in the config file for printing out the top-k candidates after the beam search. 

If it still needs to be implemented, point me to where I can modify it in the code. 

Thanks 

Carlos

**Comment by bittremieux** [comment]
This is functionality that is under active development, see #139. It will be included in the next Casanovo release.
