### ISSUE TITLE
Replace the `--mode` argument with subcommands

### ISSUE THREAD

**Issue by wfondrie** [Noble-Lab/casanovo#157]
Currently, casanovo relies on the required `--mode` argument to know what to do. I propose replacing this with subcommands so that:

- `casanovo --mode denovo ...` becomes `casanovo run ...`
- `casanovo --mode train ...` becomes `casanovo train ...`
- `casanovo --mode eval ...` becomes `casanovo evaluate ...`

Please note that this would be a *breaking change.*

**Comment by bittremieux** [comment]
Fixed in #184.
