### ISSUE TITLE
Question: Mztab score meanings 

### ISSUE THREAD

**Issue by Nkts007** [Noble-Lab/casanovo#179]
Hi I was wondering if you can help me with understanding the different columns with scores, the 'opt_ms_run[1]_aa_scores' and the 'search_engine_score[1]'.

 I have ran my own files in and underneath the 'search engine score' column, there are negative values. I was wondering if you could help me understand this?

**Comment by bittremieux** [comment]
- search_engine_score[1]: This is the score for the full peptide. Negative peptide scores arise from predictions that do not fit the precursor mass tolerance, in which case the score is penalized.
- opt_ms_run[1]_aa_scores: These are the scores for the individual amino acids in the peptide sequence, separated by comma's.

We are still in the process of updating our documentation with this information (#27).

**Comment by wsnoble** [comment]
The model outputs a confidence score between 0 and 1. We subtract 1 if the predicted m/z is outside the specified m/z window.
