### ISSUE TITLE
charge state issues

### ISSUE THREAD

**Issue by wsnoble** [Noble-Lab/casanovo#180]
Casanovo skips over scans that don't have an associated charge state.  This is perfectly reasonable, but I observed for one file that the resulting mzTab numbered the PSMs sequentially, rather than by their index in the MGF file.  This is problematic, since it makes it very difficult to tell which line in the mzTab file corresponds to which spectrum in the input file.

I tried to make a minimal example to demonstrate this behavior.  The attached file contains six spectra, of which only the fourth and sixth have an assigned charge state. I was expecting to get two PSMs in my mzTab file, and I wanted to see what scan numbers they were assigned.

However, to my dismay, Casanovo makes no predictions at all on this file.  So we first need to figure out why it's skipping all six of these spectra. Then we can try to address the scan indexing issue.

The command was `casanovo --mode=denovo --peak_path=sample.mgf --output casanovo.sample --config config.yaml`

I am attaching the relevant files.

[casanovo.log.txt](https://github.com/Noble-Lab/casanovo/files/11357916/casanovo.log.txt)
[casanovo.mztab.txt](https://github.com/Noble-Lab/casanovo/files/11357917/casanovo.mztab.txt)
[config.yaml.txt](https://github.com/Noble-Lab/casanovo/files/11357918/config.yaml.txt)
[sample.mgf.txt](https://github.com/Noble-Lab/casanovo/files/11357919/sample.mgf.txt)

**Comment by bittremieux** [comment]
I can't reproduce this with `HEAD` on #181. Casanovo correctly reports that 4 spectra have been skipped ([depthcharge#29](https://github.com/wfondrie/depthcharge/pull/29)) and the mzTab file contains output for two spectra with spectrum reference `ms_run[1]:index=2` and `ms_run[1]:index=5`.

I assume some of the logging/skipping changes have already addressed any related issues.
