### ISSUE TITLE
proper way to add additional modifications

### ISSUE THREAD

**Issue by asalt** [Noble-Lab/casanovo#192]
I tried to add some TMT labels to the config file

```
"K+229.1629": 357.257895
  # N-terminal modifications.
  "+229.1629": 229.162932 # TMT6/10/11
```

But I do not see them in the log output when running "denovo". 
This probably is because default model wasn't trained with these modifications?

So is this the proper solution: train a new model with search results from this particular experiment and use that model result to do the prediction? I then use this new prediction ckpt file.

Also regarding "train_from_scratch" - is this only for training new models? So if I want to train a new model with transfer learning I should set this to false before training?

**Comment by bittremieux** [comment]
1. Yes, you will need to train a new model to incorporate additional modifications. Changing the config file is insufficient, as Casanovo also needs to learn the corresponding spectrum patterns. Note that config options that can be modified during inference are marked with `(I)` in the config file, as described in the header, whereas all other config options necessitate training a new model.
2. Correct, to do transfer learning, you would set `train_from_scratch` to false to finetune an existing model.
