### ISSUE TITLE
How to use modification information?

### ISSUE THREAD

**Issue by javamng** [Noble-Lab/casanovo#198]
I want to give new modification information
: I modified config_1.yaml to clear the existing modification information and give a new modification as shown below.
  "K+6.02": 134.114963 # K Heavy Labeling : 128.094963 + 6.02
  "R+6.02": 162.121111 # R Heavy Labeling : 156.101111 + 6.02

I also added the --config config_1.yaml option to the command and ran it.

However, the running log doesn't show the modification I gave it, and it still shows up in the log even though I've removed the other modifications.

Below is a capture of that part

residues = {'G': 57.021464, 'A': 71.037114, 'S': 87.032028, 'P': 97.052764, 'V': 99.068414, 'T': 101.04767, 'c+57.021': 160.030649, 'L': 113.084064, 'I': 113.084064, 'N': 114.042927, 'D': 115.026943, 'Q': 128.058578, 'K': 128.094963, 'E': 129.042593, 'M': 131.040485, 'H': 137.058912, 'F': 147.068414, 'R': 156.101111, 'Y': 163.063329, 'W': 186.079313, 'M+15.995': 147.0354, 'N+0.984': 115.026943, 'Q+0.984': 129.042594, '+42.011': 42.010565, '+43.006': 43.005814, '-17.027': -17.026549, '+43.006-17.027': 25.980265}

**Comment by bittremieux** [comment]
Casanovo will only be able to use a new amino acid alphabet (including new modifications) if you train it with those settings. Hence, you would need to change the config file (like you did), and then train it using known spectra that include those modifications.

This is also indicated by the fact that the `residues` option is not marked with `(I)` in the config file, and thus cannot be modified without training a new model.
