### ISSUE TITLE
Tensorboard is not working

### ISSUE THREAD

**Issue by wsnoble** [Noble-Lab/casanovo#203]
When I train a model with tensorboard turned on, I get a numpy error about mismatched dimensions:

```
casanovo --mode=train --config config.yaml --peak_path=target.train.100k.mgf --peak_path_val=target.train.100k.mgf
...
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
```

The full stderr output, as well as the input file and the config file, are attached.  This same command works fine if I turn off tensorboard output in the config file.

[stderr.txt](https://github.com/Noble-Lab/casanovo/files/11931615/stderr.txt)
[config.txt](https://github.com/Noble-Lab/casanovo/files/11931616/config.txt)
[target.train.100k.mgf.txt](https://github.com/Noble-Lab/casanovo/files/11931617/target.train.100k.mgf.txt)

**Comment by bittremieux** [comment]
Can you try to change `metric_value` in [this line](https://github.com/Noble-Lab/casanovo/blob/26b08cf4ba6f09bd64a2bbddb8c1975788cdbe4e/casanovo/denovo/model.py#L918C36-L918C48) to `metric_value.cpu()` and see if it works then?

**Comment by wsnoble** [comment]
I tried this:

```
                   metric_value = metrics.get(key, np.nan)
                    if not np.isnan(metric_value):
                        self.tb_summarywriter.add_scalar(
                            descr, metric_value.cpu(), metrics["step"]
                        )
```

The behavior remains unchanged.

**Comment by cfmelend** [comment]
Was able to replicate this bug with the same solution working for me.

**Comment by bittremieux** [comment]
Apparently it works on `dev`, closing.
