### ISSUE TITLE
--output versus model_save_folder_path

### ISSUE THREAD

**Issue by wsnoble** [Noble-Lab/casanovo#210]
I want to run Casanovo and store the resulting series of models in a directory called `target`, and I want to store the log file in a file called `target.log`.  Casanovo has a bug that makes it think that the parameter provided to the `--output` option is a filename, as opposed to the root of the filename.  Hence, since the `target` subdirectory already exists, I get this error:

```
casanovo --mode=train --config config.target.yaml --peak_path=target-head10k.train.mgf --peak_path_val=target-head10k.test.mgf --output target
Usage: casanovo [OPTIONS]
Try 'casanovo --help' for help.

Error: Invalid value for '--output': File 'target' is a directory.
```

The workaround is obvious (I name my log file something else), but this should be fixed.

**Comment by wsnoble** [comment]
Incidentally, I think perhaps we should rename `--output` to be something like `--output-prefix`, just to be clear about what it does.

**Comment by bittremieux** [comment]
Already fixed on `dev`.
