### ISSUE TITLE
Use types for our command line arguments and improve --help doc

### ISSUE THREAD

**Issue by melihyilmaz** [Noble-Lab/casanovo#22]
Right now, all of them say TEXT - For example, the --mode option looks like it takes two choices, but I don’t know what those are purely from looking at the help (in general, if an option has two choices, it would be better served by a flag instead). Try to be more descriptive with those options and improve documentation for --help.

**Comment by VarunAnanth2003** [comment]
Added fix for this issue, on varun branch
