### ISSUE TITLE
User's custom residue vocab not loaded

### ISSUE THREAD

**Issue by AmirAlavi** [Noble-Lab/casanovo#228]
It looks like the validation logic in `config.py` never actually overwrites the `self._params["residues"]` with the value in `self._user_config`. Specifically, [validate_param](https://github.com/Noble-Lab/casanovo/blob/fba790d0abe3f9fad1041ed4185ff90043af8c2f/casanovo/config.py#L87C27-L87C27) is never called for "residues".

Quick fix is to add `residues=dict,` to the [`_config_types` dictionary](https://github.com/Noble-Lab/casanovo/blob/fba790d0abe3f9fad1041ed4185ff90043af8c2f/casanovo/config.py#L35C16-L35C16). The value (`dict`) will be ignored because the "residues" key is special-cased in the validation, but that should be fine (I think the exception will be triggered if it's not a dict).

Cause of #227.

**Comment by bittremieux** [comment]
Thanks for the detailed bug report and suggested fix. I've made the appropriate changes, and the fix will be available in the next major Casanovo release.
