### ISSUE TITLE
Terminal mods predicted mid-peptide

### ISSUE THREAD

**Issue by wsnoble** [Noble-Lab/casanovo#232]
The current version of Casanovo produces predictions that have ammonia losses scattered throughout, and not just on the N-terminus. Check out this guy, for example:

`L-17.027LK+42.011+42.011-17.027-17.027-17.027LYK+42.011-17.027-17.027+42.011L-17.027YN+43.006-17.027+43.006-17.027LLA+42.011+42.011+43.006-17.027-17.027-17.027+42.011KDNLGD-17.027+42.011LRGLGKLLNKTLGSRKGGFTGELVDLSC+57.021LG`

Once the current set of bugs is sorted out, we should take a well-trained Casanovo model and investigate whether any such peptides receive high scores or correspond to spectra that are successfully identified via database search. If they do, then perhaps we need to implement some strategy for preventing them from being reported, either in the decoding step (not ideal, since that code is already quite complex) or during post-processing.  At the very least, we should be sure that all such peptides receive negative scores.

**Comment by wsnoble** [comment]
We now discard beams with internal N terminal modifications during decoding [here](https://github.com/Noble-Lab/casanovo/blob/1bf9cdfb2392fb0100dd23a11d39e617ff074dba/casanovo/denovo/model.py#L367).

I verified that this is working correctly by looking at the prediction files for the nine-species benchmark.

**Comment by bittremieux** [comment]
That code has been in place since Casanovo v3.3.0, whereas you reported seeing these incorrect N-terminal modifications several months later. Did you possibly run an outdated version of Casanovo during the summer, or might this issue still linger somewhere?

**Comment by wsnoble** [comment]
It is certainly possible that I did run an outdated version.  OTOH, the fact that these don't show up in any of the predictions for the entire 9-species benchmark gives me some hope that maybe the problem has been eliminated.
