### ISSUE TITLE
Issue an error for unrecognized config file entries

### ISSUE THREAD

**Issue by wsnoble** [Noble-Lab/casanovo#236]
We recently renamed one of the parameters in the config file, and I used an old config file for a while without realizing that one of my parameters was incorrect and hence having no effect. I think we should modify the config file parser so that if the file contains any unrecognized entries, Casanovo stops with an error.

It should also stop with an error if there any of the expected entries is missing.

**Comment by ishagokhale** [comment]
resolved through PR #257
