### ISSUE TITLE
Casanovo makes no predictions when n_beams = 1

### ISSUE THREAD

**Issue by justin-a-sanders** [Noble-Lab/casanovo#240]
On the current dev branch, when I run Casanovo in denovo with n_beams set to 1 casanovo makes no predictions and I get an empty output file. However, everything works as expected and I get predictions when n_beams > 1. 

Here is the command I am running:

`casanovo --mode=denovo --peak_path=../data/small_train_peps.mgf --output ../results/sanders_9-1-23/n_beams_test --config config.yaml`

And here is the test dataset I experience the issue with:
[https://drive.google.com/file/d/1OJqlmKwr6g_2U6OLCfuqFt-EAqibd1NA/view?usp=sharing](https://drive.google.com/file/d/1OJqlmKwr6g_2U6OLCfuqFt-EAqibd1NA/view?usp=sharing)

**Comment by wsnoble** [comment]
This happened before:

https://github.com/Noble-Lab/casanovo/issues/185

**Comment by justin-a-sanders** [comment]
Was on wrong branch - inference with n_beams=1 works as expected on current dev branch.
