### ISSUE TITLE
precursor_mass_tol is being ignored

### ISSUE THREAD

**Issue by wsnoble** [Noble-Lab/casanovo#245]
I can't seem to change the behavior of the precursor mass filter, even if I set the precursor_mass_tol to a ridiculously large value.  Here is a small example where I set it to 1e10, and there are still negative scores.

We should also provide (or document, if it exists) a way to turn off the filter entirely.

Also, separately, it seems like the auto-download of the model only works for the `train` command.  When I try it with `sequence` I get `ValueError: A model file must be provided`.

[sample.mztab.txt](https://github.com/Noble-Lab/casanovo/files/12684785/sample.mztab.txt)
[sample.mgf.txt](https://github.com/Noble-Lab/casanovo/files/12684786/sample.mgf.txt)
[sample.log.txt](https://github.com/Noble-Lab/casanovo/files/12684787/sample.log.txt)
[casanovo.yaml.txt](https://github.com/Noble-Lab/casanovo/files/12684788/casanovo.yaml.txt)

**Comment by melihyilmaz** [comment]
Opened a PR to fix the two bugs but functionality to turn off filter entirely currently doesn't exist and it might be non-trivial to implement since it's intertwined with decoding procedure so I'm opening a new enhancement issue to cover that later.
