### ISSUE TITLE
 enzymatic digestion by enzymes other than trypsin

### ISSUE THREAD

**Issue by MengTingHe2023** [Noble-Lab/casanovo#248]
Hi, I have data for enzymatic digestion by enzymes other than trypsin, such as AspN and GluC. Do you recommend a specific model, or should I train a new model ？

**Comment by melihyilmaz** [comment]
Hi, you can try the [casanovo_non-enzy.checkpt](https://github.com/Noble-Lab/casanovo/releases/download/v3.0.0/casanovo_non-enzy.checkpt) model in release [v3.0.0](https://github.com/Noble-Lab/casanovo/releases/tag/v3.0.0) to sequence non-tryptic data. This model was obtained by fine-tuning the original tryptic model on a dataset without any enzymatic bias. (see our [preprint](https://www.biorxiv.org/content/10.1101/2023.01.03.522621v2) for me details)

If you decide that you need an enzyme-specific model, you can fine-tune the same model with the data you have.

**Comment by MengTingHe2023** [comment]
Thank you for your response and advice.
