### ISSUE TITLE
Document input and output

### ISSUE THREAD

**Issue by melihyilmaz** [Noble-Lab/casanovo#27]
On [README.md](https://github.com/Noble-Lab/casanovo/blob/main/README.md) and on the website.

**Comment by melihyilmaz** [comment]
We have  
> Casanovo can predict peptide sequences for MS/MS spectra in mzML, mzXML, and MGF files. This will write peptide predictions for the given MS/MS spectra to the specified output file in mzTab format

in the `Getting Started` page

**Comment by bittremieux** [comment]
Yes, but I think @wsnoble also wanted a brief description of what the output mzTab file looks like. So explain what information is included in the metadata and PSM sections.

**Comment by wsnoble** [comment]
Yes.  I think it would be helpful to explain what the various columns mean.  If possible, please also include pointers to descriptions of the mzML, mzXML, MGF and mzTab format specifications.
