### ISSUE TITLE
Allow for flexible GPU selection

### ISSUE THREAD

**Issue by gdewael** [Noble-Lab/casanovo#281]
Hi!

The `config.yaml` only allows the "device" to be set to an `int`, (according to https://github.com/Noble-Lab/casanovo/blob/fb6fef2d7b63001a36b199fe2b8595ee69cf17ee/casanovo/config.py#L73).

In PyTorch Lightning, it is possible to specify which GPU you want to use via a list (e.g. [3, 5] to use the third and fifth GPUs, or even [6] to select 1 specifically).

Perhaps `validate_param` can be rewritten to handle the `device` parameter separately?

**Comment by gdewael** [comment]
I've added [a pull request](https://github.com/Noble-Lab/casanovo/pull/282) to address this issue.

**Comment by bittremieux** [comment]
A workaround is to set `CUDA_VISIBLE_DEVICES` to the GPU identifier(s) that you want to use, and then allow Casanovo to use all (visible) devices.

**Comment by bittremieux** [comment]
Fixed in 6ee6351. (Accidentally pushed directly to `main`. 😳)

Instructions on how to set `devices` in the config file in combination with `CUDA_VISIBLE_DEVICES` are now included in the [FAQ](https://casanovo.readthedocs.io/en/latest/faq.html#gpu-troubleshooting).
