### ISSUE TITLE
Retrain for Viruses

### ISSUE THREAD

**Issue by lutfia95** [Noble-Lab/casanovo#287]
Hi, 

I would like to retrain Casanovo for Viruses peptide sequencing. I already tested the pre-trained model, but the generated peptides were not very good. So I would like to retrain the complete model on viruses dataset, so that the inference might be better. Would you recommend me training dataset, which is specifically for viruses? I searched online and many of them are only for SARS-Cov2. 

Best,
Ahmad

**Comment by wsnoble** [comment]
Sorry, we don't have any particular expertise w.r.t. viruses.  You would need to find published, high quality data from which you can extract a relevant set of viral PSMs.  My only suggestion is that you should not try to train from scratch but instead fine tune our existing model using your viral dataset.

**Comment by lutfia95** [comment]
thank you, I will try so. 

Best
