### ISSUE TITLE
Add more detailed installation instructions

### ISSUE THREAD

**Issue by melihyilmaz** [Noble-Lab/casanovo#30]
- This should tell users what they need to have installed before installing casanovo (Python >= 3.7, < 3.10). 
- Add instructions on how to set up a python/conda enviroment to install casanovo.
- It should also link to PyTorch so users can install the version appropriate for their GPU and CUDA version.

**Comment by vivatsal** [comment]
Hi, I would like to work on this issue.

**Comment by melihyilmaz** [comment]
Hi @vivatsal,

Thank you for your interest in Casanovo! You can for modify the `README.md` in your fork/branch to add more installation instructions as described and submit a pull request.
