### ISSUE TITLE
Question about tracking spectra from MGF files in output

### ISSUE THREAD

**Issue by JannikSchneider12** [Noble-Lab/casanovo#309]
Hello,

I have seen in other topics that it is not trivial to extract and keep track of scannumbers from MGF files since there is no unified standard. My output shows a positional index in the "spectra_ref" column. So the entries are something like "ms_run[1]:index=0" etc.

Is it right that this is the positional index for the input MGF file and thus can be used to annotate the spectra with the predicted sequences?

Thanks for your time and help

**Comment by melihyilmaz** [comment]
Yes, this refers to the positional index in the MGF file and you can use to map Casanovo outputs to input spectra.
