### ISSUE TITLE
Automate mzTab validation

### ISSUE THREAD

**Issue by wsnoble** [Noble-Lab/casanovo#323]
To be sure our mzTab stays compliant, we should incorporate the [validator](https://apps.lifs-tools.org/mztabvalidator/) into our github actions. This should be done after resolving issues [322](https://github.com/Noble-Lab/casanovo/issues/322) and [201](https://github.com/Noble-Lab/casanovo/issues/201).

**Comment by wsnoble** [comment]
Is this already done?

**Comment by bittremieux** [comment]
No.

**Comment by Lilferrit** [comment]
Unfortunately I couldn't for the life of me find a binary for the jmzTab cli. I also tried cloning the jmzTab repo and building the binary from source, but unfortunately jmzTab has dependencies that seem to be no longer publicly available.

**Comment by wsnoble** [comment]
Who wrote it? Can we reach out to the authors to ask about its status?

**Comment by Lilferrit** [comment]
The jmzTab rep (https://github.com/PRIDE-Utilities/jmzTab) has been archived and has been read only for about 2 years now which tells me they don't intend on maintaining jmzTab anymore. I can try to reach out to the original authors and see if they have access to a binary still.

**Comment by Lilferrit** [comment]
Unfortunately the link they have to the binaries is also broken on the jmzTab-M repository. I also wasn't able to successfully build the binary on windows but I have access to an ubuntu machine so I'll try it on there as well.

**Comment by bittremieux** [comment]
The [jar from here](https://github.com/bigbio/jmzTab/releases/tag/v3.0.10) seems to work. It's nowhere advertised, I just found it through Google, and compiling it myself also didn't work, so the provenance is maybe a bit questionable. But it did correctly complain about the floating point charges in older mzTab outputs and was happy after I fixed that.

```
java -jar jmzTabValidator-3.0.10-SNAPSHOT.jar -check inFile=sample.mztab
```

Maybe you can try to set up an mzTab validation workflow with this?
