### ISSUE TITLE
WARNING: Skipped spectra with invalid precursor info

### ISSUE THREAD

**Issue by lutfia95** [Noble-Lab/casanovo#326]
Hey, 

in which cases are the spectra skipped due to invalid precursor info? I have dataset which contains some not cleaned data and not sure if there is any way to clean/pre-process it. 

Best,
Ahmad

**Comment by wsnoble** [comment]
Casanovo will skip spectra for three reasons:

1. The spectrum contains fewer than 20 peaks,

2. The charge state is larger than the maximum allowed charge state (as per `max_charge`), or

3. The spectrum itself is misformatted and can't be parsed.

We are working on making the minimum number of peaks configurable [here](https://github.com/Noble-Lab/casanovo/issues/264) and on giving more details about the skipped spectra.
