### ISSUE TITLE
9-Species Benchmark Set: Data Preprocessing Step?

### ISSUE THREAD

**Issue by CCranney** [Noble-Lab/casanovo#333]
Hi,

first of all, thank you for developing this package. It is truly groundbreaking work.

I am interested in experimenting with various tweaks to see if they enhance the performance of Casanovo, and am trying to recreate training the 9-species benchmark dataset. I downloaded the data, and as an initial run-through (just to make sure it works) I ran the following line of code:

```bash
casanovo train MSV000090982/peak/Bacillus-subtilis/150710_QEp_PK_Bsub_DG_Br1.mgf -p MSV000090982/peak/H.-sapiens/151009_exo3_1.mgf
```

However, I am consistently running into problems, such as the format of amino acid modifications being inconsistent between what casanovo expects and what the Massive dataset provides (more details down below). I am doing patchwork fixes on my end, but I was wondering **_if there were specific data preprocessing steps you employed to get Casanovo to work on this dataset that are not part of its native functionality_**. If so, could you share them for parties interested in recreating your original training, possibly on the [FAQ section that details downloading and using this dataset](https://casanovo.readthedocs.io/en/latest/faq.html#training-casanovo)?

<details>
<summary><h3>Error trace and debug logic</h3></summary>

The first error to pop up was unrecognized tokens found in the 9-species benchmark dataset. 

```bash
module.py 1527 _call_impl
return forward_call(*args, **kwargs)

transformers.py 422 forward
tokens = [self.tokenize(s) for s in sequences]

transformers.py 422 <listcomp>
tokens = [self.tokenize(s) for s in sequences]

transformers.py 183 tokenize
tokens = [self._aa2idx[aa] for aa in sequence]

transformers.py 183 <listcomp>
tokens = [self._aa2idx[aa] for aa in sequence]

KeyError:
N[0.98]
```

I compared the sequences as they appear in the datasets with the amino acids (plus expected modifications) in the configs.yaml file, and realized the modifications are formatted differently. I included the following values under `residues` to bypass this error.

```python
residues:
# ...
  "C+57.021": 160.030649 # 103.009185 + 57.021464
  "C": 160.030649 # copy
# ...
  "M+15.995": 147.035400    # Met oxidation:   131.040485 + 15.994915
  "N+0.984": 115.026943     # Asn deamidation: 114.042927 +  0.984016
  "Q+0.984": 129.042594     # Gln deamidation: 128.058578 +  0.984016
  "M[15.99]": 147.035400    # copy
  "N[0.98]": 115.026943     # copy
  "Q[0.98]": 129.042594     # copy
```

After making these changes it would run begin training without throwing out any errors. However, the loss values began returning `nan`. It could be a separate issue, which I'm investigating, but I'm pretty sure the problem is in the peptide decoder. Seeing as that portion relates to choosing `residues`, I am wondering if my copy-paste fix is behind the issue. Regardless, I thought this merited creating an issue on the repository.
</details>

**Comment by wsnoble** [comment]
Sorry about this.  We made a new version of the 9-species benchmark which is available [here:](https://doi.org/doi:10.25345/C52V2CK8J) that fixes the PTM formatting issue.  Can you try using that version?

**Comment by bittremieux** [comment]
Hi Caleb, the peptide sequences in the dataset are indeed formatted a bit different than what Casanovo expects. See #283 for more information on how to convert them.

We have a fixed version of the data ready, however, some problems with updating datasets on MassIVE has so far prevented us from releasing it.

@wsnoble Caleb is already using this dataset, but it's the Tide vs ProForma notation of the peptides that's the problem.

**Comment by CCranney** [comment]
Thank you both so much! Sorry I missed that old issue - glad to see I'm not the only one to encounter the problem 👍 I'll try to revise accordingly

**Comment by bittremieux** [comment]
I've now updated the dataset on MassIVE as well, and the files that are directly compatible with the current version of Casanovo are present in the `/MSV000090982/updates/2024-05-14_woutb_71950b89/peak/9speciesbenchmark` folder. That should save ou a bit of effort by not having to mess around with converting the peptide sequences.

**Comment by tuanle618** [comment]
Potentially relevant #125
