### ISSUE TITLE
Is there a way to know which spectras are ITMS instead of FTMS?

### ISSUE THREAD

**Issue by Heisenburger2020** [Noble-Lab/casanovo#338]
In the training set of Casanovo v2, particularly within some data from ProteomeTools, there are numerous ITMS spectra instead of the higher-quality FTMS spectra.

While the files provided seem to theoretically reference the original papers for these datasets, some papers do not specify whether their datasets are ITMS or FTMS. Do you have any method to differentiate between ITMS and FTMS spectra (aside from those identified in ProteomeTools, which can be identified by the title of spectra)?

**Comment by bittremieux** [comment]
This metadata is unfortunately not available.

One benefit of the positional embedding used by Casanovo is that it doesn't require discretizing the m/z values or explicitly incorporating a fragment m/z tolerance. Instead, Casanovo inherently learns to account for the fragment m/z precision for both ITMS and FTMS data.

**Comment by Heisenburger2020** [comment]
Thank you for your reply your explanation and your great effort to maintain such a detailed repo!

![image](https://github.com/Noble-Lab/casanovo/assets/65890878/5071f969-9b92-47ab-b44b-0b0db4efec28)

Out of curiosity, I wonder how ms2 peaks are annotated. In the LIBRARY_CREATION_AUGMENT_LIBRARY_TEST-82c0124b-candidate_library_spectra-main.tsv file, how is annotated_peak_count counted? How can I reproduce number_of_ions_annotated_above_SNR? 

For example, I noticed that for some spectra, I can not get a match through the [pLabel software](http://pfind.org/software/pLabel/index.html) with an error tol 20ppm. With 0.5Da error tol, I can get a full match(between peaks and by ions). How should I choose the error tol?  (I wish to select some PSMs with too many missing peaks for some evaluation.) 

Best,
Jiale Zhao

**Comment by bittremieux** [comment]
We don't use the number of matched peaks in Casanovo. This information stems from the original dataset compilation as detailed in [Wang et al.](https://www.sciencedirect.com/science/article/pii/S2405471218303193), and was presumably obtained using analysis with MSGF+. The necessary fragment m/z tolerance will depend on the dataset, but because all Casanovo analyses are performed downstream, we don't have or need this specific information.
