### ISSUE TITLE
About depthcharge

### ISSUE THREAD

**Issue by lbwfff** [Noble-Lab/casanovo#37]
Hi, 

I use `pip install git+https://github.com/Noble-Lab/casanovo.git#egg=casanovo` code to install casanovo, Then I ran into some trouble, the following is my error message:
```
ERROR: Could not find a version that satisfies the requirement depthcharge-ms (unavailable) (from casanovo) (from versions: none)
ERROR: No matching distribution found for depthcharge-ms (unavailable)
```
I also tried installing from `https://github.com/wfondrie/depthcharge`, But it doesn't seem to work properly. The following is the error message:
`ModuleNotFoundError: No module named 'depthcharge.embed'`
how can I solve this problem?

Thanks,
LeeLee

**Comment by melihyilmaz** [comment]
Hi Lee,

You need the depthcharge version at `4bbf7702d8fdbf71327fa706627f4796fe906147` as specified in `setup.cfg` file so you need that version (i.e. installing directly from `https://github.com/wfondrie/depthcharge` gives you the latest version) but it's weird that `pip install` doesn't automatically install this and gives you an error. Would you mind sharing the full output?

@VarunAnanth2003 can you try to replicate this behavior with a fresh installation.

**Comment by lbwfff** [comment]
Hi,

I added the mirror when installing with pip, that solved the installation problem, now I have no problem.

Thanks,
LeeLee
