### ISSUE TITLE
Missing Training Data for Vigna mungo Species in MASSIVE FTP

### ISSUE THREAD

**Issue by tangz7725** [Noble-Lab/casanovo#393]
Thanks for sharing the code!

According to the [documentation](https://casanovo.readthedocs.io/en/latest/faq.html#training-casanovo), Training Casanovo there would be nine-species benchmark dataset on this ftp link: (ftp://massive.ucsd.edu/v05/MSV000090982/updates/2024-05-14_woutb_71950b89/peak/9speciesbenchmark/), 
but I have found that while there are indeed folders for eight species, the folder for the Vigna mungo species is missing.

I wonder if there is an alternative source for obtaining the Vigna mungo training data.

Thank you for your attention to this issue, and I look forward to your response!

**Comment by bittremieux** [comment]
Yes, this species is indeed currently missing. We have been waiting on a response of the MassIVE team to update the data and hopefully this will be resolved soon.

**Comment by wsnoble** [comment]
Note that there is an updated version of this benchmark associated with this preprint:

https://chemrxiv.org/engage/chemrxiv/article-details/66d24fef20ac769e5f672ad0

The benchmark is at 

https://doi.org/10.5281/zenodo.12819175
