### ISSUE TITLE
PeptideDecoder

### ISSUE THREAD

**Issue by XiaojieGan** [Noble-Lab/casanovo#395]
Hi! Where is the code of "PeptideDecoder"? I failed to find it in depthcharge.

**Comment by bittremieux** [comment]
Casanovo is currently still using an older version of DepthCharge which we are in the process of updating (#350). The `PeptideDecoder` is available in DepthCharge v0.2.x [here](https://github.com/wfondrie/depthcharge/blob/2bfd7f146a6d47c19f54fa7d2b71d88915b56169/depthcharge/components/transformers.py#L324).

**Comment by XiaojieGan** [comment]
> Casanovo is currently still using an older version of DepthCharge which we are in the process of updating (#350). The `PeptideDecoder` is available in DepthCharge v0.2.x [here](https://github.com/wfondrie/depthcharge/blob/2bfd7f146a6d47c19f54fa7d2b71d88915b56169/depthcharge/components/transformers.py#L324).

OK，thanks. And what is "precursors" referenced in Decoder?

**Comment by bittremieux** [comment]
You mean in the `forward` function? Precisely as described in the docstring:
> precursors : torch.Tensor of size (batch_size, 2)
>    The measured precursor mass (axis 0) and charge (axis 1) of each tandem mass spectrum

**Comment by XiaojieGan** [comment]
> You mean in the `forward` function? Precisely as described in the docstring:
> 
> > precursors : torch.Tensor of size (batch_size, 2)
> > The measured precursor mass (axis 0) and charge (axis 1) of each tandem mass spectrum

I can't understand what is "precursors" stands for.

**Comment by bittremieux** [comment]
The information from the MS1 scan.
