### ISSUE TITLE
Embedding function

### ISSUE THREAD

**Issue by XiaojieGan** [Noble-Lab/casanovo#396]
Equation.1 and code were mismatched. Which version was you implement?

**Comment by bittremieux** [comment]
I assume you are referring to the sinusoidal embeddings for the m/z and intensity values? The version in the code is correct, as this has been through a few changes since the paper (e.g. #145).

**Comment by XiaojieGan** [comment]
> I assume you are referring to the sinusoidal embeddings for the m/z and intensity values? The version in the code is correct, as this has been through a few changes since the paper (e.g. #145).

Oh，thank you,I see. The version I'm looking at does use a pre-modification formula
