### ISSUE TITLE
Number of spectra in mgf do not match number of results in mztab

### ISSUE THREAD

**Issue by Heisenburger2020** [Noble-Lab/casanovo#398]
Dear Sir,

command I used: casanovo sequence --output trial.mztab trial.mgf

Is there a way to output the title of spectra? the id does not seem to be user-friendly and not easy to debug.

Best,
Jiale

**Comment by Heisenburger2020** [comment]
I counted 443281 spectras in a mgf file, casanovo notryptic outputs 443273 spectras, casanovo default outputs 443261. Both experiments got 443281spectra while loading. I can not understand why is this happening.

**Comment by Heisenburger2020** [comment]
I see, I found a column can identify the spectra corresponding to mgf spectra.

**Comment by bittremieux** [comment]
Some spectra might be omitted if they are of too low quality. The next Casanovo release will output more informative messages on the command-line on the number of spectra that have been skipped.

You can match rows in the mzTab output to your input spectra based on the `spectra_ref` column. For MGF files, this column contains 0-based index values of the spectra. This is also detailed in the documentation on the [page describing the Casanovo file formats](https://casanovo.readthedocs.io/en/latest/file_formats.html#output-understanding-the-mztab-format).
