### ISSUE TITLE
About output file

### ISSUE THREAD

**Issue by lbwfff** [Noble-Lab/casanovo#40]
Hi,
This question may be a little silly. In the peptides of the output file, there are peptides such as "C+57.021GHTNNLRPK". I don't quite understand what "+57.021" means. The peptide predicted by the algorithm is "CGHTNNLRPK" or there are some unknown amino acid between C and GHTNNLRPK?

```
0 | LAHYNKR | 0.991221964
1 | VKEDPDGEAHR | 0.965903959
2 | C+57.021GHTNNLRPK | 0.991358876
3 | VVQEQGTHPK | 0.987940228
4 | KGKPELR | 0.991316216
5 | SLSHSPGK | 0.993293308

```

Thanks,
LeeLee

**Comment by wsnoble** [comment]
In most tandem mass spectrometry experiments, the amino acid cysteine has a modification applied to it as part of the sample processing.  This modification, called [carbamidomethylation](https://www.sigmaaldrich.com/US/en/technical-documents/technical-article/protein-biology/protein-labeling-and-modification/peptide-modifications-n-terminal-internal-and-c-terminal), adds 57.021 Da to the mass of cysteine. This annotation simply reflects that mass shift.
