### ISSUE TITLE
[Hypotheses]Fine-tuning to add new PTMs using the PEFT algorithm

### ISSUE THREAD

**Issue by PYxuejiang** [Noble-Lab/casanovo#405]
Dear Development Team

Greetings! I have noticed a statement in the documentation that reads, "It is unfortunately not possible to finetune a pre-trained Casanovo model to add new types of PTMs. Instead, such a model must be trained from scratch" , I would like to inquire if there are corresponding experiments to support this statement, or is it a theoretical deduction? Currently, there are many efficient fine-tuning methods available, such as the PEFT algorithm. If we were to employ an algorithm like this and freeze pre-trained weights for fine-tuning, would it be possible to add new types of PTMs?

**Comment by bittremieux** [comment]
Hi @PYxuejiang, you are indeed correct that Casanovo can potentially be finetuned for new PTMs. This statement primarily reflects technical limitations, in that this functionality is currently not implemented yet, rather than that this is not possible at all.

Expanding Casanovo to a wider diversity of PTMs is on our (long-term) roadmap.

**Comment by PYxuejiang** [comment]
> 嗨，您确实是对的，Casanovo 可能会针对新的 PTM 进行微调。此声明主要反映了技术限制，因为此功能当前尚未实现，而不是根本不可能。
> 
> 将 Casanovo 扩展到更广泛的 PTM 在我们的（长期）路线图上。

Thank you very much for your response and for your efforts in creating such an outstanding model like Casanovo. I would like to inquire if your team has plans to build an easy-to-use fine-tuning platform for users in the future. If there are similar ideas, that would be fantastic. I hope to have the opportunity to discuss the approach!

**Comment by bittremieux** [comment]
We are currently busy at work to incorporate various improvements for the next Casanovo release. Finetuning for novel PTMs is not an active endeavor, but will be tackled in the future. We are always open to discussing ideas already, or even accepting contributions through a PR.
