### ISSUE TITLE
No mudule named pytest

### ISSUE THREAD

**Issue by yingluoqiao** [Noble-Lab/casanovo#41]
![casanovo_issue](https://user-images.githubusercontent.com/103443560/180752915-65625948-f40e-48cf-86f9-342d5c78d778.png)

**Comment by bittremieux** [comment]
You can fix this error by running `pip install pytest` in your Casanovo conda environment.

However, somehow not all dependencies seem to have been installed alongside Casanovo, which is weird. It seems like you followed the installation instructions in the README, or did you deviate from them somewhere?

Alternatively, can you uninstall and reinstall Casanovo using `pip uninstall casanovo && pip install git+https://github.com/Noble-Lab/casanovo.git#egg=casanovo` and share the output here?

**Comment by yingluoqiao** [comment]
Hi
 Thanks for your reply. I followed the instruction in the READMR fully. I will try out!

Best
Weiwei

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Wout Bittremieux ***@***.***>
发送时间: 星期一, 七月 25, 2022 5:54 下午
收件人: Noble-Lab/casanovo ***@***.***>
抄送: Peng, W. (Weiwei) ***@***.***>; Author ***@***.***>
主题: Re: [Noble-Lab/casanovo] No mudule named pytest (Issue #41)

你通常不会收到来自 ***@***.*** 的电子邮件。了解这一点为什么很重要<https://aka.ms/LearnAboutSenderIdentification>

You can fix this error by running pip install pytest in your Casanovo conda environment.

However, somehow not all dependencies seem to have been installed alongside Casanovo, which is weird. It seems like you followed the installation instructions in the README, or did you deviate from them somewhere?

Alternatively, can you uninstall and reinstall Casanovo using pip uninstall casanovo && pip install git+https://github.com/Noble-Lab/casanovo.git#egg=casanovo and share the output here?

―

**Comment by bittremieux** [comment]
Fixed in #55.
