### ISSUE TITLE
Casanovo perfomance improvement

### ISSUE THREAD

**Issue by CrystalColeCrystal** [Noble-Lab/casanovo#413]
Hello!

I have been using Casanovo (_nontryptic.ckpt weights) for my immunopeptidomics samples analysis along with Fragpipe (https://github.com/Nesvilab/FragPipe), which is a database search tool. I am really interested in setting up an efficient pipeline of de novo sequencing but so far my number of hits on uniprot was significantly smaller compared to Fragpipe (for example: ~300 unique peptides matching uniprot for Casanovo vs ~1100 unique peptides matching uniprot for Fragpipe). I attach my .yaml config file here for reference. Do you have any suggestions on the parameters I should use to improve Casanovo performance? Would finetuning it on more data significantly improve the results? If so, how much data is needed for a notable change?
[casanovo_config.txt](https://github.com/user-attachments/files/18038400/casanovo_config.txt)

Thank you so much for your help!

**Comment by wsnoble** [comment]
In general, the choice of whether to use a de novo or database search approach depends strongly on the data and, in particular, the quality of your peptide database.  In particular, you should try to estimate what proportion of the spectra in your dataset are likely to be generated by a peptide in the database (which we refer to as "native" spectra) as opposed to spectra that are generated by peptides not in the database ("foreign" spectra).  For example, if you sequence data from a well characterized organism (e.g., human) then you might expect >99% of your spectra to be native.  In that case, de novo sequencing is going to have a very difficult time competing with a database search.  On the other hand, if you analyze a metaproteomics sample from an obscure source for which you have no corresponding metagenomic sequencing data available, then some relatively large proportion of your spectra (>50%) may be foreign.  In that case, de novo may be the way to go.

Regarding finetuning, the answer here depends on how different your data is from the data that was used to train Casanovo.  If you are using fairly "standard" data, then finetuning may not make much of a difference.  The only way to be sure is to try some fine tuning and see if it helps.  We have not done extensive experiments with finetuning, so it's hard to say a priori how much labeled data you would need.  I would guess that you'd need on the order of 10k labeled spectra for it to be worthwhile, but that's pure guesswork.

**Comment by CrystalColeCrystal** [comment]
Thank you very much for your answer!

I addition, I would like to ask is there any recommended pipeline for downstream analysis? I'm not entirely sure if my routine is perfect and I would like to ask your opinion. For example, I have noticed that if I look for Uniprot hits allowing I to L and L to I substitutions (as I'm sure you know they are indistinguishable in MS) I get twice more hits. Is it a good practice to do that? Would it also make sense to allow 1 any mismatch when mapping hits back to the database? Also, I filter out all peptide that have search_engine_score<0. Is it a good idea to do so?

**Comment by wsnoble** [comment]
For downstream analysis, you can put your results into Limelight.

https://limelight-ms.readthedocs.io/en/latest/

Yes, if you are matching to a peptide database, then you should allow I<->L matches.

More generally, allowing more mismatches may be a good idea depending on what you want to do with your results. Any de novo sequencing tool will make some common mistakes of, e.g., swapping the order of two adjacent amino acids.

As for choosing a score threshold, that also depends what you want to do with your results. The ones with negative scores have ppm error outside your specified range (default=50 ppm).  If you are using the development version of Casanovo, we now have better calibrated scores, so you can roughly interpret the score as the probability of correctness (e.g., 90% of the matches with score >0.9 will be correct).

**Comment by CrystalColeCrystal** [comment]
Thank you!

Could you please list other common mistakes (such as swapping the order of two adjacent amino acids) to account for while mapping back to the database?

**Comment by wsnoble** [comment]
I think the most common form of error is to reverse adjacent pairs of amino acids, so e.g., PEPTIDEK -> PETPIDEK.  Beyond this, another common error modality is to confuse isobaric pairs of amino acids.  Here is a listing of single and pairs of amino acids with mass differences less than 10 ppm:

```
kmer1 kmer2 mass1       mass2       ppm
GG    N     114.1038    114.1038    0.0000
AG    Q     128.1307    128.1307    0.0000
AS    GT    158.1570    158.1570    0.0000
GL    AV    170.2113    170.2114    0.5875
GQ    AN    185.1826    185.1826    0.0000
AD    EG    186.1674    186.1674    0.0000
LS    TV    200.2376    200.2377    0.4994
AM    CV    202.2714    202.2714    0.0000
QS    NT    215.2089    215.2089    0.0000
DT    ES    216.1937    216.1937    0.0000
LN    QV    227.2632    227.2633    0.4400
DL    EV    228.2480    228.2481    0.4381
DQ    EN    243.2193    243.2193    0.0000
DK    GW    243.2627    243.2651    9.8658
GW    RS    243.2651    243.2657    2.4664
EK    AW    257.2896    257.2920    9.3280
AW    RT    257.2920    257.2926    2.3320
FH    QR    284.3177    284.3182    1.7586
```

**Comment by CrystalColeCrystal** [comment]
Thank you so much for your help!
