### ISSUE TITLE
config.yaml in small walkthrough example

### ISSUE THREAD

**Issue by wsnoble** [Noble-Lab/casanovo#42]
I just tried to run the "small walkthrough" that's in the Casanovo readme, but it didn't work.  I thought it was strange that the example makes no mention of the yaml configuration file.  Sure enough, when I ran the example, I got an error message saying it couldn't find that file:

```
casanovo --mode=denovo --model_path=../../../data/22-07-02_weights/pretrained_excl_mouse.ckpt --test_data_path=mgf
/net/noble/vol1/home/noble/miniconda3/envs/casanovo_env/lib/python3.7/site-packages/torch/cuda/__init__.py:83: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 9010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at  ../c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo_env/bin/casanovo", line 8, in <module>
    sys.exit(main())
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo_env/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo_env/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo_env/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo_env/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo_env/lib/python3.7/site-packages/casanovo/casanovo.py", line 58, in main
    with open(abs_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/net/noble/vol1/home/noble/miniconda3/envs/casanovo_env/lib/python3.7/site-packages/casanovo/config.yaml'
```

We need to update the README to describe how to set up the config file.

**Comment by bittremieux** [comment]
Currently, when no config file is given, [the code tries to find a default config file in the same directory as the script](https://github.com/Noble-Lab/casanovo/blob/main/casanovo/casanovo.py#L57). If we don't package a (fully functional) config file with Casanovo, this doesn't make a lot of sense imo.

We could:

- Include a default config file. It might be a bit challenging to come up with sensible default values for all options, but it's probably possible.
- Change the code so that it gives a more informative error message, rather than look for a non-existing file.
- In each case, update the documentation accordingly so that this is more clearly described.

**Comment by VarunAnanth2003** [comment]
I updated the tutorial to tell the user how to make their own config file. However, a default already exists and it is supposed to be accessed with these lines:
```python
if config_path == None:
        abs_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'config.yaml')
        with open(abs_path) as f:
            config = yaml.safe_load(f)

**Comment by bittremieux** [comment]
There are two problems with the default config file:

- It's not packaged along with the source code, so will not be available by default after installing with pip.
- It does not always work out of the box (i.e. fails if you don't have a GPU). Especially when the config file is hidden in some internal package directory, this is challenging for people to find and modify.

**Comment by VarunAnanth2003** [comment]
How can I modify the repo so that the config.yaml is packaged and placed in its proper place with a pip install? I'll also update the default values.

**Comment by bittremieux** [comment]
You have to specify non-Python files you want included using a [MANIFEST.in file](https://packaging.python.org/en/latest/guides/using-manifest-in/).
