### ISSUE TITLE
code for generating decoy peptides

### ISSUE THREAD

**Issue by rxnataliezhang** [Noble-Lab/casanovo#420]
I reviewed the db_search function in the development branch but couldn’t find any code related to generating decoy peptides. Could you please direct me to where it’s located? Additionally, does the resulting .mztab file from casanovo-db only include peptides detected at a 1% FDR threshold?

**Comment by bittremieux** [comment]
Casanovo currently doesn't include functionality to generate decoy peptides. Instead you can use several external tools to generate such a database. Similarly, so far no FDR filtering is performed by Casanovo, but rather all top-scoring assignments for every spectrum will be reported.

These functionalities will likely be added in the (near) future, but as mentioned previously, the Casanovo-DB implementation should currently still be considered as an early prototype.
