### ISSUE TITLE
By default, Casanovo should do precursor filtering

### ISSUE THREAD

**Issue by wsnoble** [Noble-Lab/casanovo#84]
According to Melih, Casanovo still does not do precursor filtering by default.  I think we should always do precursor filtering and never allow the user to get results that do not have the filter applied (i.e., 1 should be subtracted from the confidence score if the predicted m/z is outside the user-specified precursor m/z tolerance).

**Comment by bittremieux** [comment]
[Predictions that are not within the precursor m/z tolerance are in fact always penalized.](https://github.com/Noble-Lab/casanovo/blob/main/casanovo/denovo/model.py#L445)

**Comment by wfondrie** [comment]
Could Melih be referring to isotope errors?

**Comment by melihyilmaz** [comment]
I raised this point earlier when Bo said he had fewer peptide predictions than the number of spectra he was putting into the model, which made me suspect if we weren't returning a peptide prediction for a spectrum if predicted peptide was outside of the precursor mass range. In the meantime, I've spent more time with the code and this doesn't seem to be the case, a penalty of 1 is subtracted as Wout pointed out.

That being said, my current beam search implementation doesn't return any predictions if no peptides within the mass range are predicted for a spectrum, should I change that to be inline with our current "keep the peptide, subtract from confidence score"?

**Comment by bittremieux** [comment]
I think that we should always return _n_ peptides for each spectra (with _n=1_ default). If Casanovo doesn't find any peptides that match the precursor m/z, the scores will be penalized but the predictions might still be useful (unknown modification, contaminants, ...).

**Comment by wsnoble** [comment]
I agree with Wout.

**Comment by melihyilmaz** [comment]
Ok, I will modify my implementation accordingly.
