### ISSUE TITLE
Defining Output Terminology

### ISSUE THREAD

**Issue by kostrouc** [Noble-Lab/casanovo#95]
May you explain how the **search_engine_score[1]** and the **opt_ms_run[1]_aa_scores** are calculated and how to evaluate these metrics? I don't see this in the listed publication or documentation links.

Thank you!

**Comment by melihyilmaz** [comment]
Hi Katherine,

In the output mzTab:

- `opt_ms_run[1]_aa_scores` corresponds to amino-acid level confidence scores - this can be treated as a probability measure of how likely model deems the predict amino to be and is output by the model.
- `search_engine_score[1]` corresponds to peptide-level confidence scores which is obtained by averaging over amino acid-level confidence scores along the peptide.

**Comment by kostrouc** [comment]
So for the search_engine_score does this mean that if we want to be 90% confident that the predicted peptide sequence is not due to chance, this score should be 0.90 ?

**Comment by melihyilmaz** [comment]
Not exactly since the underlying amino acid confidence scores aren't _actual_ probabilities. However, in practice, you can treat it as such.
